# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# set darkmode
config.set("colors.webpage.darkmode.enabled", True)


# colors
# https://github.com/Linuus/cac-qutebrowser/blob/c7f89c0991bdb8e02ede67356355cd9ae891d2be/cac-qutebrowser.py
cac = {
    # __cac:start
    "background": "#1a1b26",
    "foreground": "#a9b1d6",
    "dim_black": "#06080a",
    "dim_red": "#e06c75",
    "dim_green": "#98c379",
    "dim_yellow": "#d19a66",
    "dim_blue": "#7aa2f7",
    "dim_magenta": "#ad8ee6",
    "dim_cyan": "#56bdb8",
    "dim_white": "#abb2bf",
    "bright_black": "#24283b",
    "bright_red": "#f7768e",
    "bright_green": "#9ece6a",
    "bright_yellow": "#e0af68",
    "bright_blue": "#61afef",
    "bright_magenta": "#f6bdff",
    "bright_cyan": "#50c3bd",
    "bright_white": "#ffffff",
    # __cac:end
}

## Background color of the completion widget category headers.
## Type: QssColor
c.colors.completion.category.bg = cac["background"]

## Bottom border color of the completion widget category headers.
## Type: QssColor
c.colors.completion.category.border.bottom = cac["background"]

## Top border color of the completion widget category headers.
## Type: QssColor
c.colors.completion.category.border.top = cac["background"]

## Foreground color of completion widget category headers.
## Type: QtColor
c.colors.completion.category.fg = cac["dim_white"]

## Background color of the completion widget for even rows.
## Type: QssColor
c.colors.completion.even.bg = cac["bright_black"]

## Background color of the completion widget for odd rows.
## Type: QssColor
c.colors.completion.odd.bg = cac["bright_black"]

## Text color of the completion widget.
## Type: QtColor
c.colors.completion.fg = cac["foreground"]

## Background color of the selected completion item.
## Type: QssColor
c.colors.completion.item.selected.bg = cac["dim_white"]

## Bottom border color of the selected completion item.
## Type: QssColor
c.colors.completion.item.selected.border.bottom = cac["dim_white"]

## Top border color of the completion widget category headers.
## Type: QssColor
c.colors.completion.item.selected.border.top = cac["dim_white"]

## Foreground color of the selected completion item.
## Type: QtColor
c.colors.completion.item.selected.fg = cac["foreground"]

## Foreground color of the matched text in the completion.
## Type: QssColor
c.colors.completion.match.fg = cac["dim_yellow"]

## Color of the scrollbar in completion view
## Type: QssColor
c.colors.completion.scrollbar.bg = cac["bright_black"]

## Color of the scrollbar handle in completion view.
## Type: QssColor
c.colors.completion.scrollbar.fg = cac["dim_white"]

## Background color for the download bar.
## Type: QssColor
c.colors.downloads.bar.bg = cac["background"]

## Background color for downloads with errors.
## Type: QtColor
c.colors.downloads.error.bg = cac["bright_red"]

## Foreground color for downloads with errors.
## Type: QtColor
c.colors.downloads.error.fg = cac["dim_white"]

## Color gradient stop for download backgrounds.
## Type: QtColor
c.colors.downloads.stop.bg = cac["dim_magenta"]

## Color gradient interpolation system for download backgrounds.
## Type: ColorSystem
## Valid values:
##   - rgb: Interpolate in the RGB color system.
##   - hsv: Interpolate in the HSV color system.
##   - hsl: Interpolate in the HSL color system.
##   - none: Don't show a gradient.
c.colors.downloads.system.bg = "none"

## Background color for hints. Note that you can use a `rgba(...)` value
## for transparency.
## Type: QssColor
c.colors.hints.bg = cac["dim_yellow"]

## Font color for hints.
## Type: QssColor
c.colors.hints.fg = cac["background"]

## Font color for the matched part of hints.
## Type: QssColor
c.colors.hints.match.fg = cac["bright_blue"]

## Background color of the keyhint widget.
## Type: QssColor
c.colors.keyhint.bg = cac["bright_black"]

## Text color for the keyhint widget.
## Type: QssColor
c.colors.keyhint.fg = cac["dim_white"]

## Highlight color for keys to complete the current keychain.
## Type: QssColor
c.colors.keyhint.suffix.fg = cac["dim_yellow"]

## Background color of an error message.
## Type: QssColor
c.colors.messages.error.bg = cac["bright_red"]

## Border color of an error message.
## Type: QssColor
c.colors.messages.error.border = cac["bright_red"]

## Foreground color of an error message.
## Type: QssColor
c.colors.messages.error.fg = cac["dim_white"]

## Background color of an info message.
## Type: QssColor
c.colors.messages.info.bg = cac["bright_blue"]

## Border color of an info message.
## Type: QssColor
c.colors.messages.info.border = cac["bright_blue"]

## Foreground color an info message.
## Type: QssColor
c.colors.messages.info.fg = cac["background"]

## Background color of a warning message.
## Type: QssColor
c.colors.messages.warning.bg = cac["bright_yellow"]

## Border color of a warning message.
## Type: QssColor
c.colors.messages.warning.border = cac["bright_yellow"]

## Foreground color a warning message.
## Type: QssColor
c.colors.messages.warning.fg = cac["dim_white"]

## Background color for prompts.
## Type: QssColor
c.colors.prompts.bg = cac["bright_black"]

# ## Border used around UI elements in prompts.
# ## Type: String
c.colors.prompts.border = "1px solid " + cac["background"]

## Foreground color for prompts.
## Type: QssColor
c.colors.prompts.fg = cac["dim_white"]

## Background color for the selected item in filename prompts.
## Type: QssColor
c.colors.prompts.selected.bg = cac["dim_white"]

## Background color of the statusbar in caret mode.
## Type: QssColor
c.colors.statusbar.caret.bg = cac["dim_magenta"]

## Foreground color of the statusbar in caret mode.
## Type: QssColor
c.colors.statusbar.caret.fg = cac["dim_white"]

## Background color of the statusbar in caret mode with a selection.
## Type: QssColor
c.colors.statusbar.caret.selection.bg = cac["dim_magenta"]

## Foreground color of the statusbar in caret mode with a selection.
## Type: QssColor
c.colors.statusbar.caret.selection.fg = cac["dim_white"]

## Background color of the statusbar in command mode.
## Type: QssColor
c.colors.statusbar.command.bg = cac["bright_black"]

## Foreground color of the statusbar in command mode.
## Type: QssColor
c.colors.statusbar.command.fg = cac["dim_white"]

## Background color of the statusbar in private browsing + command mode.
## Type: QssColor
c.colors.statusbar.command.private.bg = cac["bright_black"]

## Foreground color of the statusbar in private browsing + command mode.
## Type: QssColor
c.colors.statusbar.command.private.fg = cac["dim_white"]

## Background color of the statusbar in insert mode.
## Type: QssColor
c.colors.statusbar.insert.bg = cac["bright_green"]

## Foreground color of the statusbar in insert mode.
## Type: QssColor
c.colors.statusbar.insert.fg = cac["bright_black"]

## Background color of the statusbar.
## Type: QssColor
c.colors.statusbar.normal.bg = cac["background"]

## Foreground color of the statusbar.
## Type: QssColor
c.colors.statusbar.normal.fg = cac["dim_white"]

## Background color of the statusbar in passthrough mode.
## Type: QssColor
c.colors.statusbar.passthrough.bg = cac["bright_blue"]

## Foreground color of the statusbar in passthrough mode.
## Type: QssColor
c.colors.statusbar.passthrough.fg = cac["dim_white"]

## Background color of the statusbar in private browsing mode.
## Type: QssColor
c.colors.statusbar.private.bg = cac["dim_white"]

## Foreground color of the statusbar in private browsing mode.
## Type: QssColor
c.colors.statusbar.private.fg = cac["dim_white"]

## Background color of the progress bar.
## Type: QssColor
c.colors.statusbar.progress.bg = cac["dim_white"]

## Foreground color of the URL in the statusbar on error.
## Type: QssColor
c.colors.statusbar.url.error.fg = cac["bright_red"]

## Default foreground color of the URL in the statusbar.
## Type: QssColor
c.colors.statusbar.url.fg = cac["dim_white"]

## Foreground color of the URL in the statusbar for hovered links.
## Type: QssColor
c.colors.statusbar.url.hover.fg = cac["bright_blue"]

## Foreground color of the URL in the statusbar on successful load
## (http).
## Type: QssColor
c.colors.statusbar.url.success.http.fg = cac["dim_white"]

## Foreground color of the URL in the statusbar on successful load
## (https).
## Type: QssColor
c.colors.statusbar.url.success.https.fg = cac["bright_green"]

## Foreground color of the URL in the statusbar when there's a warning.
## Type: QssColor
c.colors.statusbar.url.warn.fg = cac["bright_yellow"]

## Background color of the tab bar.
## Type: QtColor
c.colors.tabs.bar.bg = cac["dim_white"]

## Background color of unselected even tabs.
## Type: QtColor
c.colors.tabs.even.bg = cac["dim_white"]

## Foreground color of unselected even tabs.
## Type: QtColor
c.colors.tabs.even.fg = cac["dim_white"]

## Color for the tab indicator on errors.
## Type: QtColor
c.colors.tabs.indicator.error = cac["bright_red"]

## Color gradient start for the tab indicator.
## Type: QtColor
# c.colors.tabs.indicator.start = cac['violet']

## Color gradient end for the tab indicator.
## Type: QtColor
# c.colors.tabs.indicator.stop = cac['orange']

## Color gradient interpolation system for the tab indicator.
## Type: ColorSystem
## Valid values:
##   - rgb: Interpolate in the RGB color system.
##   - hsv: Interpolate in the HSV color system.
##   - hsl: Interpolate in the HSL color system.
##   - none: Don't show a gradient.
c.colors.tabs.indicator.system = "none"

## Background color of unselected odd tabs.
## Type: QtColor
c.colors.tabs.odd.bg = cac["dim_white"]

## Foreground color of unselected odd tabs.
## Type: QtColor
c.colors.tabs.odd.fg = cac["dim_white"]

# ## Background color of selected even tabs.
# ## Type: QtColor
c.colors.tabs.selected.even.bg = cac["background"]

# ## Foreground color of selected even tabs.
# ## Type: QtColor
c.colors.tabs.selected.even.fg = cac["dim_white"]

# ## Background color of selected odd tabs.
# ## Type: QtColor
c.colors.tabs.selected.odd.bg = cac["background"]

# ## Foreground color of selected odd tabs.
# ## Type: QtColor
c.colors.tabs.selected.odd.fg = cac["dim_white"]


### Things I haven't changed

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)


# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set("content.cookies.accept", "all", "chrome-devtools://*")

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set("content.cookies.accept", "all", "devtools://*")

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set("content.headers.accept_language", "", "https://matchmaker.krunker.io/*")

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}",
    "https://web.whatsapp.com/",
)

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version} Edg/{upstream_browser_version}",
    "https://accounts.google.com/*",
)

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36",
    "https://*.slack.com/*",
)

# Load images automatically in web pages.
# Type: Bool
config.set("content.images", True, "chrome-devtools://*")

# Load images automatically in web pages.
# Type: Bool
config.set("content.images", True, "devtools://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "chrome-devtools://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "devtools://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "chrome://*/*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "qute://*/*")
