#!/bin/bash
# generates a dunstrc file
# necessary because the dunstrc format doesn't support color variables

# __cac:start
background="#1a1b26"
foreground="#a9b1d6"
dim_black="#06080a"
dim_red="#e06c75"
dim_green="#98c379"
dim_yellow="#d19a66"
dim_blue="#7aa2f7"
dim_magenta="#ad8ee6"
dim_cyan="#56bdb8"
dim_white="#545a75"
bright_black="#24283b"
bright_red="#f7768e"
bright_green="#9ece6a"
bright_yellow="#e0af68"
bright_blue="#61afef"
bright_magenta="#f6bdff"
bright_cyan="#50c3bd"
bright_white="#a9b1d6"
# __cac:end

config="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc"

rm $config

cat << CONF > $config
[global]
  ### Display ###
  monitor = 0
  follow = keyboard

  transparency = 10
  width = 300
  origin = bottom-right
  offset = 6x46
  indicate_hidden = yes
  shrink = no
  separator_height = 3
  padding = 12
  horizontal_padding = 12
  frame_width = 2

  separator_color = frame
  sort = yes
  idle_threshold = 120
  mouse_right_click = close_all


  ### Text ###
  font = Lato
  line_height = 0

  markup = full

  # The format of the message.  Possible variables are:
  #   %a  appname
  #   %s  summary
  #   %b  body
  #   %i  iconname (including its path)
  #   %I  iconname (without its path)
  #   %p  progress value if set ([  0%] to [100%]) or nothing
  #   %n  progress value if set without any extra characters
  #   %%  Literal %
  # Markup is allowed
  format = "<b>%s </b>\n%b"
  alignment = left
  vertical_alignment = center
  show_age_threshold = 60
  word_wrap = yes
  ellipsize = middle
  ignore_newline = no
  stack_duplicates = true
  hide_duplicate_count = false
  show_indicators = yes

  icon_position = left
  min_icon_size = 32
  max_icon_size = 32

  icon_path = /usr/share/icons/BeautyLine/devices/scalable:/usr/share/icons/BeautyLine/apps/scalable


  ### History ###
  sticky_history = yes
  history_length = 50

  ### Misc/Advanced ###
  dmenu = /usr/bin/dmenu dunst:
  browser = $BROWSER
  always_run_script = true
  title = Dunst
  class = Dunst
  force_xinerama = false

[urgency_low]
  foreground = "$foreground"
  background = "$background"
  frame_color = "$background"

[urgency_normal]
  foreground = "$foreground"
  background = "$background"
  frame_color = "$background"

[urgency_critical]
  background = "$background"
  foreground = "$foreground"
  frame_color = "$bright_red"

[spotify]
  appname = "Spotify"  # using appname is bad practice, but spotify doesn't give us a desktop entry
  skip_display = true
  script = "spotify-notification"

# vim:ft=cfg
CONF
