# template: letter
# note that structured variables may be specified:
metadata:
  author:
    - Riley Shahar
  geometry: margin=1in

include-in-header:
  - /home/riley/.config/pandoc/header-include.tex
