swipe:
  3:
    left:
      command: "qtile cmd-obj -o screen -f next_group"
    right:
      command: "qtile cmd-obj -o screen -f prev_group"
    down:
      command: "qtile cmd-obj -o screen -f toggle_group"
    up:
      command: "qtile cmd-obj -o screen -f toggle_group"
