swipe:
  3:
    left:
      command: "/home/riley/dotfiles/bin/wmh ws n"
    right:
      command: "/home/riley/dotfiles/bin/wmh ws p"
    down:
      command: "swaymsg workspace "
    up:
      command: "swaymsg workspace "
