name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        run: pip install poetry

      - name: Generate lockfile
        run: poetry lock

      - name: Install nox
        run: pip install nox nox-poetry

      - name: Run nox
        run: nox --sessions test-3.10 coverage
        env:
          CODECOV_TOKEN: ${{ '{{secrets.CODECOV_TOKEN}}' }}
