name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    name: Python ${{ '{{ matrix.python-version }}' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up python ${{ '{{ matrix.python-version }}' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ '{{ matrix.python-version }}' }}

      - name: Install poetry
        run: pip install poetry

      - name: Generate lockfile
        run: poetry lock

      - name: Install nox
        run: pip install nox nox-poetry

      - name: Run nox
        run: nox --python ${{ '{{ matrix.python-version }}' }}
